### ISSUE TITLE
Refactor cloudify.swarm.Microservice

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-examples/cloudify-swarm-plugin#2]
- [ ] Create a ```cloudify.datatypes.swarm.Template``` data type. It should accept either a path to a file or inline. If a file is used, use ctx.download_resource_and_render to allow templates.
```yaml
data_types:
  cloudify.datatypes.swarm.Template:
    properties:
      filepath:
        description: a Docker Compose file.
        required: false
      inline:
        description: If using in
        required: false
```
- [ ] Create a ```cloudify.datatypes.swarm.Microservice``` data type:
```yaml
data_types:
  cloudify.datatypes.swarm.Microservice:
    properties:
      template:
         type: cloudify.datatypes.swarm.Template
         required: true
```
- [ ] Refactor the ```cloudify.swarm.Microservice``` node type:
```
  cloudify.swarm.Microservice:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_external_resource:
        type: boolean
        default: false
      resource_id:
        description: the name of the service
        type: string
        required: false
      resource_config:
        type: cloudify.datatypes.swarm.Microservice
    interfaces:
      cloudify.interfaces.lifecycle:
        create: swarm.swarm_plugin.tasks.add_microservice
        start: swarm.swarm_plugin.tasks.start_service
        delete: swarm.swarm_plugin.tasks.rm_service
```
